#!/bin/sh
### BEGIN INIT INFO
# Provides: nginx
### END INIT INFO

#chkconfig: 345 20 80
#description: nginx web-server

set -e 

NAME=nginx
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/nginx

DAEMON=/usr/local/nginx/$NAME
DAEMON_NAME=$NAME
DAEMON_DESC=$NAME
PIDFILE=/var/run/$DAEMON_NAME.pid
CONFIG=/usr/local/nginx/nginx.conf


case "$1" in
    start)
      if start-stop-daemon --stop --quiet --signal 0 --pidfile $PIDFILE
      then
        echo "running"
        exit 0
      fi      
      echo -n "Starting $DAEMON_DESC: "
      touch $PIDFILE
      chown $NAME:$NAME $PIDFILE
      if start-stop-daemon --start --quiet --exec $DAEMON 
      then
        echo "$DAEMON_NAME started."
      else
        echo "failed"
      fi
      ;;
    stop)
      echo -n "Stopping $DAEMON_DESC: "
      if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
      then
        echo "$DAEMON_NAME stopped."
      else
        echo "failed"
      fi
      rm -f $PIDFILE
      ;;
    restart)
      ${0} stop
      ${0} start
      ;;
    configtest)
      $DAEMON -t
      ;;
    status)
      echo -n "$DAEMON_DESC is "
      if start-stop-daemon --stop --quiet --signal 0 --pidfile $PIDFILE
      then
        echo "running"
      else
        echo "not running"
        #exit 1
      fi
      ;;
    *)
      echo "Usage: /etc/init.d/$NAME {start|stop|restart|configtest|status}" >&2
      exit 1
      ;;
esac

exit 0  
